[project]
name = "Blockchain-worker"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
  "fastapi>=0.121.0",
  "uvicorn>=0.34.0",
  "pycryptodome>=3.20.0",
  "Crypto",
  "pydantic>=2.0.0",
  "jinja2>=3.1.0",
]
